### ISSUE TITLE
Easier way to get the result

### ISSUE THREAD

**Issue by vaclavgreif** [BulkGate/message#1]
Currently, there's no easy way to get the transaction result. We have to do something like this to check if there were some errors:

		try {
			$response = $this->sender->send( new \BulkGate\Sms\Message( $number, $text ) ); 
			/** @var $response \BulkGate\Message\Response */
			if ($response->__isset('error'))
				return new \WP_Error('500',$response->__get('error'));
			
			return $response;

		} catch ( \Exception $e ) {
			return new \WP_Error('500',$e->getMessage());
		}

It would be great to have some helper method to get the transaction result.

**Comment by lukaspijak** [comment]
On version 2.0.1/1.0.1 is added isSuccess() method.

		try {
			$response = $this->sender->send( new \BulkGate\Sms\Message( $number, $text ) ); 
			/** @var $response \BulkGate\Message\Response */
			if (!$response->isSuccess())
				return new \WP_Error('500',$response->error);
			
			return $response;

		} catch ( \Exception $e ) {
			return new \WP_Error('500',$e->getMessage());
		}
