### ISSUE TITLE
Class Request  is incompatible with PHP <7.1 (branch 1.0)

### ISSUE THREAD

**Issue by RadH-CZ** [BulkGate/message#2]
src/Message/Request.php is incompatible with PHP <7.1
On line 16 and 18 is wrong const definition.
"public const" generate
`Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)`

**Comment by lukaspijak** [comment]
Hello, 

if you use php 7.0 you must install version 1.0. Version 2.0 is for php 7.1+.

https://github.com/BulkGate/message/blob/master/composer.json#L18

```sh
composer require bulkgate/message "^1.0"
```

or

```sh
composer require bulkgate/sms "^1.0"
```

Features are same.

**Comment by RadH-CZ** [comment]
I have php 7.0 installed using "bulkgate/sms": "^1.0" in composer
But even in version 1.0, "public const" is used:
https://github.com/BulkGate/message/blob/v1.0/src/Message/Request.php#L16

**Comment by RadH-CZ** [comment]
The latest tag in version 1.0.2 also contains the definition of "public const":
https://github.com/BulkGate/message/blob/1.0.2/src/Message/Request.php
This will cause a parse error on PHP 7.0
